version: '2.0'
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    expose:
      - "1883"
      - "9001"
    volumes:
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"